apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: demoapp
spec:
    replicas: 2
    selector:
       matchLabels:
          tier: frontend
    template:
       metadata: 
         labels:
            tier: frontend
       spec:
         containers:
         - image: redis
           name: redis
           ports:
           - containerPort: 80